### PR TITLE
Mememefy

### PR DESCRIPTION
**Pull request by ghost**
# Welcome to Mememefy!

Mememefy detects faces with the newly released Mobile Vision API from Google and draws the meme representing the peoples current expressions over the people's faces. 

If you like it, you can send me a mail via mail@fls.link
#### AndroidManifest.xml

In order to run this demo correctly you will have to add the following lines to the AndroidManifest:

```
<uses-permission android:name="android.permission.CAMERA" />

<application

    ...

    <meta-data android:name="com.google.android.gms.version"
      android:value="@integer/google_play_services_version"/>

    <meta-data android:name="com.google.android.gms.vision.DEPENDENCIES"
      android:value="face" />

</application>
```
### Screenshots

test
test2

### CODE REVIEW

**Comment by EarlOfEgo** [comment]
:shipit:

**Comment by passsy** [comment]
awesome!

**Comment by EarlOfEgo** [comment]
[] (https://media.giphy.com/media/Qh6NZWsFx1G1O/giphy.gif)

**Comment by ouchadam** [comment]
:100:  let's do it!

**Comment by ouchadam** [comment]
will deploy play services to the node and then remerge this

**Comment by blundell** [comment]
i like :+1:

**Comment by tasomaniac** [comment]
wow!

**Pull request merged**
