### PR TITLE
Eden test

### PR DESCRIPTION
**Pull request by mikescamell**
Mike Scamell
mike@edenagency.co.uk

eden_test

### CODE REVIEW

**Comment by ryanbateman** [comment]
Hi Mike. Could you add a gif of the test in action? There's some instructions of how to do it in the README.

**Comment by mikescamell** [comment]
Added a gif into the project!

**Comment by ryanbateman** [comment]
Could you add it to your PRs description rather than in the code? Drag and drop will do it

**Comment by mikescamell** [comment]
eden_test

**Comment by mikescamell** [comment]
This what you mean? Sorry have made too many pull requests!

**Comment by mikescamell** [comment]
Just realised now where you meant, guess it's too late now!

**Comment by ryanbateman** [comment]
Looks good!

**Comment by blundell** [comment]
:+1:

**Pull request merged**
