### PR TITLE
catz

### PR DESCRIPTION
**Pull request by tasomaniac**
Really really simple test with random cat photos

screen shot 2015-10-29 at 16 39 17

### CODE REVIEW

**Comment by ryanbateman** [comment]
The pull request we needed.

**Comment by tasomaniac** [comment]
:smile_cat:

**Comment by tasomaniac** [comment]
:cat: :joy_cat:

**Comment by takecare** [comment]
L:smile_cat:TM

**Comment by ouchadam** [comment]
:100:

**Comment by blundell** [comment]
dat cat is mad

**Pull request merged**
